apiVersion: v1
kind: Service
metadata:
  name: pubsub-service
spec:
  selector:
    app: pubsub
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsub-deployment
spec:
  selector:
    matchLabels:
      app: pubsub-app
  replicas: 4
  template:
    metadata:
      labels:
        app: pubsub-app
    spec:
      containers:
      - name: pubsub-container
        image: pubsub:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
